//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::bookmarks::Entity as Bookmarks;
pub use super::favorites::Entity as Favorites;
pub use super::followers::Entity as Followers;
pub use super::following::Entity as Following;
pub use super::post_comments::Entity as PostComments;
pub use super::post_files::Entity as PostFiles;
pub use super::post_likes::Entity as PostLikes;
pub use super::posts::Entity as Posts;
pub use super::stories::Entity as Stories;
pub use super::user_links::Entity as UserLinks;
pub use super::users::Entity as Users;
