data_dir = "/var/lib/vector"

[sources.app_log]
type = "file"
ignore_older_secs = 600
include = [ "logs/*" ]
read_from = "beginning"

[sinks.parseable]
type = "http"
method = "post"
batch.max_bytes = 10485760
batch.max_events = 1000
batch.timeout_secs = 10
compression = "gzip"
inputs = ["app_log"]
encoding.codec = "json"
uri = 'https://instaclone-logs.fly.dev/api/v1/logstream/production'
auth.strategy = "basic"
auth.user = "instaclone"
auth.password = "${PARSEABLE_PASSWORD}"
healthcheck.enabled = true
healthcheck.path = 'https://instaclone-logs.fly.dev/api/v1/liveness'
healthcheck.port = 80